baseURL = "https://blog.cruru.kr/"
languageCode = "ko-kr"
title = "팀 크루루의 개발 이야기"

googleAnalyics = "G-B3P4MC2ELV"
enableRobotsTXT=true

[taxonomies]
    author = 'author'
    category = 'categories'
    keywords = 'keywords'
    series = 'series'

[module]
[[module.imports]]
path = "github.com/colinwilson/lotusdocs"
disable = false
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
disable = false

[menu]
[[menu.primary]]
name = "Infra"
url = "/docs/infra/"
identifier = "docs"
weight = 10

[[menu.primary]]
name = "Backend"
url = "/docs/backend/"
identifier = "showcase"
weight = 20

[[menu.primary]]
name = "Frontend"
url = "/docs/frontend/"
identifier = "community"
weight = 30

[params.social]
github = 'woowacourse-teams/2024-cruru'

[params.docs]
pathName = 'docs'
themeColor = 'magenta'
prism = true
prismTheme = "lucario"

[params.footer]
copyright = '© :YEAR: 우아한테크코스 6기 Cruru. <br><br>Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)'

[params.flexsearch]
enabled             = true
tokenize            = "full"

[markup.goldmark.renderer]
unsafe = true
